<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <!-- 基础项目信息 -->
    <groupId>io.github.cn-luyang</groupId>
    <artifactId>luyang-cloud</artifactId>
    <version>${revision}</version>

    <packaging>pom</packaging>

    <!-- 项目属性 -->
    <properties>
        <skipTests>true</skipTests>
        <java.version>21</java.version>
        <revision>0.0.1-SNAPSH0T</revision>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <modules>
        <module>luyang-cloud-api-uac</module>
        <module>luyang-cloud-business-plan</module>
        <module>luyang-cloud-platform-uaa</module>
        <module>luyang-cloud-platform-uac</module>
    </modules>

    <repositories>
        <repository>
            <id>snapshots-repo</id>
            <url>https://central.sonatype.com/repository/maven-snapshots/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.github.cn-luyang</groupId>
                <artifactId>dependencies</artifactId>
                <version>2025.12.13.02</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>io.github.cn-luyang</groupId>
                <artifactId>luyang-cloud-api-uac</artifactId>
                <version>${revision}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <skip>false</skip>
                </configuration>
                <executions>
                    <execution>
                        <id>repackage</id>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <compilerArgs>
                        <arg>-parameters</arg>
                    </compilerArgs>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>1.7.0</version>
                <configuration>
                    <!-- 设置扁平化模式为 'oss'（开源发布模式），仅保留必要字段如 groupId、artifactId、version 等 -->
                    <flattenMode>oss</flattenMode>
                    <!-- 是否更新项目中的 pom.xml 文件（将扁平化结果写回到 pom 文件） -->
                    <updatePomFile>true</updatePomFile>
                </configuration>
                <executions>
                    <!-- 在 process-resources 阶段执行 flatten 操作，生成扁平化后的 POM 文件，便于发布到 Maven 仓库 -->
                    <execution>
                        <!-- 扁平化执行标识 -->
                        <id>flatten</id>
                        <!-- 在处理资源阶段执行 -->
                        <phase>process-resources</phase>
                        <goals>
                            <!-- 执行扁平化操作 -->
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <!-- 在 clean 阶段执行 clean 操作，清除 flatten 生成的临时文件（如原始 pom 的备份） -->
                    <execution>
                        <!-- 清理扁平化执行标识 -->
                        <id>flatten.clean</id>
                        <!-- 在清理阶段执行 -->
                        <phase>clean</phase>
                        <goals>
                            <!-- 执行清理操作 -->
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
