<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <!-- 基础项目信息 -->
    <groupId>io.github.cn-luyang</groupId>
    <artifactId>luyang-cloud</artifactId>
    <version>${revision}</version>

    <packaging>pom</packaging>

    <!-- 项目属性 -->
    <properties>
        <skipTests>true</skipTests>
        <java.version>21</java.version>
        <revision>0.0.1-SNAPSH0T</revision>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <modules>
        <module>luyang-cloud-api-uac</module>
        <module>luyang-cloud-platform-open</module>
        <module>luyang-cloud-platform-uac</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.github.cn-luyang</groupId>
                <artifactId>dependencies</artifactId>
                <version>0.0.20-SNAPSH0T</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
